name: Test Mac wheel build

on:
  workflow_dispatch:
  push:
    branches:
      - mac-build-wheel

jobs:
  build:
    strategy:
      max-parallel: 4
      matrix:
        platform: [macos-14]
        python-version: ["3.10"]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'v0.0.27'
          submodules: recursive
          path: "."
          fetch-depth: 0 # for tags

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install locally
        run: |
          python -m pip install torch==2.3.1
          python -m pip install --upgrade pip==23.3.2
          python -m pip install wheel ninja
          brew install llvm libomp
          MACOSX_DEPLOYMENT_TARGET=10.9 CC=/opt/homebrew/opt/llvm/bin/clang CXX=/opt/homebrew/opt/llvm/bin/clang++ python -m pip wheel . -w wheels

